title: "Warp Bubble Metric Ansatz"
description: "A computational toolkit for generating and analyzing warp bubble spacetime metrics, including Alcubierre and Natário profiles with automated LaTeX documentation."
baseurl: "/warp-bubble-metric-ansatz"
url: "https://arcticoder.github.io"

# GitHub Pages settings - simplified for static files
plugins: []

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - SETUP.md
