title: "Warp Bubble Metric Ansatz"
description: "A computational toolkit for generating and analyzing warp bubble spacetime metrics, including Alcubierre and Natário profiles with automated LaTeX documentation."
baseurl: "/warp-bubble-metric-ansatz"
url: "https://arcticoder.github.io"

# GitHub Pages settings
remote_theme: jekyll/minima

# Exclude files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - SETUP.md

# Include additional file types
include:
  - "*.pdf"
  - "*.tex"
